django/common/urls.py
from django import views
from django.urls import path, reverse_lazy
from unicodedata import name
from django.contrib.auth import views as auth_views
from . import views
from .views import SignUpView

app_name = 'common'

urlpatterns = [
    
    # 로그인 "{% url 'common:login_main' %}"
    # path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login_main'), # 이건 관리자만 가능
    path('login/', views.login_main, name='login_main'),

    # 로그아웃 "{% url 'common:logout' %}"
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # 아이디 찾기 "{% url 'common:find_id' %}"
    path('find_id/', views.find_id, name='find_id'),

    # 아이디 찾기 체크완료 "{% url 'common:find_id_checked' %}"
    path('find_id/checked', views.find_id_checked, name='find_id_checked'),

    # 비밀번호 찾기
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),

    # 비밀번호 재설정 메일 전송 완료
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    # 비밀번호 재설정
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    # 비밀번호 재설정 완료
    path('password_reset_finish/', views.password_reset_finish, name='password_reset_finish'),

    # 회원가입 페이지
    path('signup/', SignUpView.as_view(), name='signup'),
    
    # 회원가입 완료 페이지 "{% url 'common:signup_completed' %}"
    path('signup/completed', views.signup_completed, name='signup_completed'),  

    # 비밀번호 수정 "{% url 'common:change_password' %}"
    path('change_password/', views.change_password, name='change_password'),

    # 비밀번호 수정 완료 "{% url 'common:modify_password_completed' %}"
    path('modify_password_completed/', views.modify_password_completed, name='modify_password_completed'),

    # 이메일 수정 "{% url 'common:modify_email' %}"
    path('modify_email/', views.modify_email, name='modify_email'),

    # 이메일 수정 "{% url 'common:modify_email_completed' %}"
    path('modify_email_completed/', views.modify_email_completed, name='modify_email_completed'),

    # 프로그램 종료 "{% url 'common:program_stop' %}"
    path('program_stop/', views.program_stop, name='program_stop'),

]

django/common/forms.py
"""
common/forms.py
"""

from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from .models import User, PostureLog


# 사용자 생성 폼
class UserCreationForm(forms.ModelForm):
    # 비밀번호 입력
    password1 = forms.CharField(label='Password', max_length=200, widget=forms.PasswordInput)
    # 비밀번호 확인
    password2 = forms.CharField(label='Password confirmation', max_length=200, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'gender', 'email', 'birth')

    # 패스워드 검증
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("비밀번호가 틀렸습니다.")
        return password2

    # 데이터 저장
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

# 사용자 수정 Form
# class UserChangeForm(forms.ModelForm):
#     # 사용자의 패스워드를 read 권한으로 설정하여 수정하지 못하도록 함
#     password = ReadOnlyPasswordHashField()
#
#     class Meta:
#         model = User
#         fields = ('username', 'gender', 'email', 'birth', 'password')
#
#     def clean_password(self):
#         return self.initial["password"]

    # class Meta:
    #     model = User
    #     fields = ('username', 'gender', 'email', 'birth', 'password')
    #
    # def clean_password(self):
    #     return self.initial["password"]

from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = '기존 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False,
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })

class CustomEmailChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email',)


class PostureLogForm(ModelForm):
    class Meta:
        model = PostureLog
        fields = '__all__'

# 비밀번호 초기화
import django.contrib.auth.forms as auth_forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
User = get_user_model()

class PasswordResetForm(auth_forms.PasswordResetForm):

    username = auth_forms.UsernameField(label="아이디")  # CharField 대신 사용

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_username(self):
        data = self.cleaned_data['username']
        if not User.objects.filter(username=data).exists():
            raise ValidationError("해당 사용자ID가 존재하지 않습니다.")
        return data

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")

        if username and email:
            if User.objects.get(username=username).email != email:
                raise ValidationError("사용자의 이메일 주소가 일치하지 않습니다.")

    def get_users(self, email=''):
        active_users = User.objects.filter(**{
            'username__iexact': self.cleaned_data["username"],
            'is_active': True,
        })
        return (
            u for u in active_users
            if u.has_usable_password()
        )

django/common/views.py
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.contrib import messages
from .forms import CustomPasswordChangeForm, CustomEmailChangeForm, PostureLogForm
import cv2
import threading
from django.shortcuts import render
import numpy as np
from django.http.response import JsonResponse, HttpResponse
from django.http import StreamingHttpResponse
import time
from common.modules import HolisticModule as hm
from win10toast import ToastNotifier
import tensorflow as tf
from keras.models import load_model
from keras.utils import np_utils
from keras.models import Sequential
from keras.preprocessing.image import img_to_array
from PIL import Image
from django.http import HttpResponse
from common import views
from django.contrib import auth, messages
from django.shortcuts import render, redirect
from .models import User, PostureLog
from django.contrib.auth.forms import PasswordChangeForm  # 비밀번호 변경 폼
from django.contrib.auth.hashers import check_password
from django.contrib.auth import update_session_auth_hash  # 비밀번호 변경 후 자동로그인
import ctypes
from django.views import View

# fps = 1초당 프레임의 수
# privious time for fps
pTime = 0
# cerrent time for fps
cTime = 0

# 모델 불러오기
model = tf.keras.models.load_model('common\\saved_model')

# Holistic 객체(어떠한 행위를 하는 친구) 생성
detector = hm.HolisticDetector()

# toast 알림을 주는 객체 생성
toaster = ToastNotifier()

# 턱 괴기 변수 초기 세팅
jaw_bone_count = 0

# 턱 괴기 교정 카운트 변수 초기 세팅
p_jaw_bone_count = 0

# 실제 턱 괴기 변수 초기 세팅
real_jaw_bone_count = 0

# 어깨 비대칭 변수 초기 세팅
shoulder_count = 0

# 어깨 비대칭 교정 카운트 변수 초기 세팅
p_shoulder_count = 0

# 실제 어깨 비대칭 변수 초기 세팅
real_shoulder_count = 0

# 양 어깨 높이 차이 변수
shoulder_hd = 0

# 거북목 변수 초기 세팅
turtleNeck_count = 0

# 거북목 교정 카운트 변수 초기 세팅
p_turtleNeck_count = 0

# 실제 거북목 변수 초기 세팅
real_turtleNeck_count = 0

# postureLog 객체 생성
postureLog = PostureLog()

app_name = 'common'


class VideoCamera(object):
    stretch_img_name = ''
    # capture mode

    mode = 0

    # stretching value
    isStretchingPose = False

    # 방향 위치 : 0(오른쪽), 1(왼쪽)
    currentDirection = 0

    # 방향 위치 : 0(위), 1(아래)
    upDown = 0

    # username
    usrname = ''

    # 입 동작 : 0(아), 1(이)
    mouth_mode = 0

    # 교정 횟수
    stretching_count = 0

    def __init__(self):
        # Using OpenCV to capture from device 0. If you have trouble capturing
        # from a webcam, comment the line below out and use a video file
        # instead.
        self.video = cv2.VideoCapture(0)
        (self.grabbed, self.frame) = self.video.read()
        threading.Thread(target=self.update, args=()).start()

    # If you decide to use video.mp4, you must have this file in the folder
    # as the main.py.
    # self.video = cv2.VideoCapture('video.mp4')

    def __del__(self):
        self.video.release()

    # 자세 인식
    def get_frame(self):
        def draw_circle(image, center, radius, color=(255, 0, 0), thickness=3, lineType=cv2.LINE_AA):
            return cv2.circle(frame, center, radius, color, thickness, lineType)

        # Holistic detector을 이용한 감지
        frame = detector.findHolistic(self.frame, draw=True)

        # output -> list ( id, x, y, z) 32 개 좌표인데 예를 들면, (11, x, y, z)
        pose_lmList = detector.findPoseLandmark(frame, draw=True)
        # 468개의 얼굴 점 리스트
        face_lmList = detector.findFaceLandmark(frame, draw=True)

        # fps 계산 로직
        cTime = time.time()
        global pTime
        fps = 1 / (cTime - pTime)
        pTime = cTime

        # 사용자의 컴퓨터에 맞는 주사율
        my_computer_fps = fps + 1

        # 웹캠 이미지 저장
        turtleNeck_frame = cv2.imwrite('frame.jpg', frame)

        # 이미지 파일 경로

        file_link = "frame.jpg"

        # 인체가 감지가 되었는지 확인하는 구문
        if len(pose_lmList) != 0 and len(face_lmList) != 0:

            # 이미지 RGB 변환 및 사이즈 조정
            img = Image.open(file_link)
            img = img.convert("RGB")
            img = img.resize((64, 64))

            # 이미지 배열화 및 차원 확장
            turtleNeck_region = img_to_array(img)
            turtleNeck_region = np.expand_dims(turtleNeck_region, axis=0)

            single_test = model.predict(turtleNeck_region)

            # Holistic_module에 있는 findDistance의 p2값을 수정하여 사용
            # 왼쪽 center_left_hand 좌표와 얼굴 152번(턱) 좌표를 사용하여 길이를 구하는 부분

            # 양쪽 손 관절점 위치를 찾는 함수
            left_hand_len = detector.findPointDistance(152, 20)
            right_hand_len = detector.findPointDistance(152, 17)

            # 양 어깨의 관절점 사이의 거리를 이미지로 변경
            shoulder_img = detector.drawShoulder(11, 12, frame, draw=True)

            # 어깨의 y값 비교하여 양 쪽 어깨의 높이가 다르면 어깨 비대칭으로 인식
            shoulder_hd = detector.findShoulder(11, 12)

            # 양쪽 손 관절점 위치를 시각화 하는 함수
            left_hand_img = detector.drawPointDistance(
                152, 20, frame, draw=True)
            right_hand_img = detector.drawPointDistance(
                152, 17, frame, draw=True)

            mouth_img = detector.drawMouth(frame, draw=True)

            mouth_img = detector.drawMouth(frame, draw=True)

            global jaw_bone_count
            global p_jaw_bone_count
            global real_jaw_bone_count
            global shoulder_count
            global p_shoulder_count
            global real_shoulder_count
            global turtleNeck_count
            global p_turtleNeck_count
            global real_turtleNeck_count

            # 턱 괴기 자세가 감지되면 턱 괴기 count 1증가
            if left_hand_len < 130 or right_hand_len < 130:
                jaw_bone_count += 1
                shoulder_count = 0
                turtleNeck_count = 0
            elif left_hand_len < 25 or right_hand_len < 25:
                jaw_bone_count = 0
            else:
                jaw_bone_count = 0

            # 어깨 비대칭 자세가 감지되면 어깨 비대칭 count 1증가
            if shoulder_hd >= 30:
                shoulder_count += 1
            else:
                shoulder_count = 0

            # 거북목이 감지되면 count가 1증가
            if single_test == 1:
                turtleNeck_count += 1
            else:
                turtleNeck_count = 0

            # 3초동안 턱 괴기 자세가 인식되면 알림을 제공한다.
            if jaw_bone_count > my_computer_fps * 3:
                # 자세 인식 후, insert DB
                self.insertLog(self.usrname, 0)

                print("턱괴기 자세가 감지되었습니다!")

                # win10toast 알림 제
                toaster.show_toast(
                    "턱 괴기 발생!", f"바른 자세를 취해주세요!.\n\n", threaded=True)

                # 알림 제공 후 카운트를 다시 0으로 만든다.
                jaw_bone_count = 0
                p_jaw_bone_count += 1
                real_jaw_bone_count += 1

            draw_circle(frame,(330,280),100,(255,0,0),3,cv2.LINE_AA)
            cv2.putText(frame, str(int(real_jaw_bone_count)), (20, 40), cv2.FONT_HERSHEY_TRIPLEX, 1, (0, 0, 255), 2)
            cv2.putText(frame, "jaw", (20, 60), cv2.FONT_HERSHEY_TRIPLEX, 0.5, (0, 0, 255), 1)
            cv2.putText(frame, str(int(real_shoulder_count)), (20, 100), cv2.FONT_HERSHEY_TRIPLEX, 1, (0, 0, 255), 2)
            cv2.putText(frame, "shoulder", (20, 120), cv2.FONT_HERSHEY_TRIPLEX, 0.5, (0, 0, 255), 1)
            cv2.putText(frame, str(int(real_turtleNeck_count)), (20, 160), cv2.FONT_HERSHEY_TRIPLEX, 1, (0, 0, 255), 2)
            cv2.putText(frame, "neck", (20, 180), cv2.FONT_HERSHEY_TRIPLEX, 0.5, (0, 0, 255), 1)
            if shoulder_count > my_computer_fps * 3:
                # 자세 인식 후, insert DB
                self.insertLog(self.usrname, 1)

                print("어깨 비대칭 동작이 감지되었습니다!")

                toaster.show_toast(
                    "어깨 비대칭 발생!", f"바른 자세를 취해주세요!", threaded=True)

                # 알림 제공 후 카운트를 다시 0으로 만듬
                shoulder_count = 0
                p_shoulder_count += 1
                real_shoulder_count += 1

            if turtleNeck_count > my_computer_fps * 3:
                # 자세 인식 후, insert DB
                self.insertLog(self.usrname, 2)

                print("거북목 동작이 감지되었습니다!")
                # win10toast 알림 제공
                toaster.show_toast(
                    "거북목 발생!", f"바른 자세를 취해주세요!.\n\n", threaded=True)

                # 알림 제공 후 카운트를 다시 0으로 만든다.
                turtleNeck_count = 0
                p_turtleNeck_count += 1
                real_turtleNeck_count += 1

            if p_shoulder_count != 0 and p_shoulder_count % 3 == 0:
                VideoCamera.mode = 1
            elif p_turtleNeck_count != 0 and p_turtleNeck_count % 3 == 0:
                VideoCamera.mode = 2
            elif p_jaw_bone_count != 0 and p_jaw_bone_count % 3 == 0:
                VideoCamera.mode = 3

        ret, jpeg = cv2.imencode('.jpg', frame)
        return jpeg.tobytes()

    # 어깨 비대칭 스트레칭
    def get_frame_stretching(self):

        global p_jaw_bone_count
        global p_shoulder_count
        global p_turtleNeck_count


        # Holistic detector을 이용한 감지
        frame = detector.findHolistic(self.frame, draw=True)

        # output -> list ( id, x, y, z) 32 개 좌표인데 예를 들면, (11, x, y, z)
        pose_lmList = detector.findPoseLandmark(frame, draw=True)
        # 468개의 얼굴 점 리스트
        face_lmList = detector.findFaceLandmark(frame, draw=True)

        # fps 계산 로직
        cTime = time.time()
        global pTime
        fps = 1 / (cTime - pTime)
        pTime = cTime

        # 사용자의 컴퓨터에 맞는 주사율
        my_computer_fps = fps + 1

        # 인체가 감지가 되었는지 확인하는 구문
        if len(pose_lmList) != 0 and len(face_lmList) != 0:

            # 양쪽 귀 관절점 사이의 거리를 이미지로 변경
            ears_img = detector.drawEars(frame, draw=True)

            # 양 어깨의 관절점 사이의 거리를 이미지로 변경
            shoulder_img = detector.drawShoulder2(frame, draw=True)

            # 양쪽 손과 눈썹 사이 거리 구하기
            left_hand_position = detector.findPointDistance2(21, 6)
            right_hand_position = detector.findPointDistance2(22, 3)
            # print(left_hand_position, right_hand_position)

            # 양쪽 귀의 기울기 값 계산
            ears_inclination = detector.findinclination(7, 8)

            if VideoCamera.isStretchingPose == True:  # 포즈가 취해졌는지 판단

django/templates/common/find_id.html
{% extends "base.html" %}
{% load static %} 
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/find_id.css' %}">

<div class="find_id">
    <h3 style="font-size: 30px;">아이디 찾기</h3>
        <form method="post" autocomplete="off">
            {% csrf_token %}
            <div class="flex">
                <ul class="container">
                    <li class="item center">
                        이메일
                    </li>
                    <li class="item">
                        <input type="email" name="email" id="email" placeholder="이메일을 입력하세요.">
                    </li>
                </ul>
                <ul class="container">
                    <li class="item center">
                    </li>
                    <li class="item">
                        <button type="Submit" class="submit">확인</button>
                    </li>
                </ul>
                {% for message in messages %}
                    {{message}}
                {% endfor %}
            </div>
    </form>
</div>
{% endblock %}

django/templates/common/find_id_checked.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/find_id_checked.css' %}">

<div id="div-logo-container">
    <div id="div-logo"></div>
</div>

<div id="div-container">

    <div id="div-wrapper">
        <div>
            <p class="p-txt"> 이메일로 아이디를 전송했습니다. </p>
        </div>
        
        <table id="table-id-list-02">
            <tr>
                &nbsp;
            </tr>
            <tr>
                &nbsp;
            </tr>
            <tr>
                <td>
                    <button id="btn-fix" onclick="location.href='{% url 'common:login_main' %}'">
                        로그인하기
                    </button>
                </td>
                <td>
                    <button id="btn-fix" onclick="location.href='{% url 'common:password_reset' %}'">
                        비밀번호 찾기
                    </button>
                </td>
            </tr>
        </table>
    </div>
</div>

{% endblock %}

django/templates/common/login.html
{% extends "base.html" %}
{% load static %} 
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

<div id="div-login">
    <form method="post" action="{% url 'common:login_main' %}">
        {% csrf_token %}
        
        <div class="form-group">
            <!-- 로그인 글자 -->
            <h1 style="text-align: left; margin-left: 50px; font-size: 30px; margin-bottom: 20px;">
                로그인
            </h1>
            
            <!-- 아이디 -->
            <input type="text" name="username" id="username" placeholder="아이디"
                   >
        </div>

        <div class="form-group">
            
            <!-- 비밀번호 -->
            <input type="password" name="password" placeholder="비밀번호" id="password"
                   >
            
        </div>
        {% include "form_errors.html" %}
            {{error}}
        <!-- 로그인 버튼 -->
        <button type="submit" id="btn-login" onclick="location.href='{% url 'common:login_main' %}'">로그인</button>
        <br>

        <a id="a-find-btn" href="{% url 'common:find_id' %}"> 아이디 찾기 </a>
        <a id="a-find-btn" href="{% url 'common:password_reset' %}"> 비밀번호 찾기 </a>
        <a id="a-register-btn" href="{% url 'common:signup' %}"> 회원가입 </a>
    </form>
</div>
{% endblock %}

django/templates/common/password_reset.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/find_id.css' %}">

<div class="find_id">
    <h3 style="font-size: 30px;">비밀번호 찾기</h3>
        <form method="post" autocomplete="off" action="{%url 'common:password_reset' %}">
            {% csrf_token %}

            <div class="flex">
                <ul class="container">
                    <li class="item center">
                        <label for="username">아이디</label>
                    </li>
                    <li class="item">
                        <input type="text" class="form-control" name="username" id="username"
                            value="{{ form.username.value|default_if_none:'' }}">
                    </li>
                </ul>
                <ul class="container">
                    <li class="item center">
                        <label for="email">이메일</label>
                    </li>
                    <li class="item">
                        <input type="text" class="form-control" name="email" id="email"
                            value="{{ form.email.value|default_if_none:'' }}">
                    </li>
                </ul>
                <ul class="container">
                    <li class="item center">
                    </li>
                    <li class="item">
                        <button type="Submit" class="submit">이메일 전송</button>
                    </li>
                </ul>
                {% for message in messages %}
                    {{message}}
                {% endfor %}
            </div>
    </form>
</div>
{% endblock %}

django/templates/common/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/find_id.css' %}">

<div class="find_id">
    <h3 style="font-size: 30px;">비밀번호 재설정</h3>
        {% if validlink %}
        <form method="post" autocomplete="off">
        {% csrf_token %}
        <div class="flex">
            <ul class="container">
                <li class="item center">
                    <label for="new_password1">새로운<br>비밀번호</label>
                </li>
                <li class="item">
                    <input type="password" name="new_password1" id="new_password1" placeholder="새로운 비밀번호를 입력하세요.">
                </li>
            </ul>
            <ul class="container">
                    <li class="item center">
                        <label for="new_password2">비밀번호<br>확인</label>
                    </li>
                    <li class="item">
                        <input type="password" name="new_password2" id="new_password2" placeholder="새로운 비밀번호를 다시 입력하세요.">
                    </li>
                </ul>
                <ul class="container">
                    <li class="item center">
                    </li>
                    <li class="item">
                        <button type="Submit" class="submit">변경하기</button>
                    </li>
                </ul>
        </div>

    </form>
    {% else %}
    <p>링크가 유효하지 않습니다.</p>
    {% endif %}
</div>
{% endblock %}

django/templates/common/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/find_id_checked.css' %}">

<div id="div-logo-container">
    <div id="div-logo"></div>
</div>

<div id="div-container">

    <div id="div-wrapper">
        <div>
            <p class="p-txt"> 이메일을 전송했습니다. </p>
        </div>

        <table id="table-id-list-02">
            <tr>
                &nbsp;
            </tr>
            <tr>
                &nbsp;
            </tr>
            <tr>
                <td>
                    <button id="btn-fix" onclick="location.href='{% url 'common:login_main' %}'">
                        로그인하기
                    </button>
                </td>
                <td>

                </td>
            </tr>
        </table>
    </div>

</div>

{% endblock %}

django/templates/common/password_reset_email.html
{% autoescape off %}
안녕하세요!
{{ user.username }} 님의 비밀번호를 재설정하기 위한 이메일입니다.
아래의 페이지에서 비밀번호를 재설정 해주세요.

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

{% endautoescape %}

django/templates/common/password_reset_finish.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/find_id_checked.css' %}">

<div id="div-logo-container">
    <div id="div-logo"></div>
</div>

<div id="div-container">

    <div id="div-wrapper">
        <div>
            <p class="p-txt"> 비밀번호 재설정을 완료했습니다. </p>
        </div>

        <table id="table-id-list-02">
            <tr>
                &nbsp;
            </tr>
            <tr>
                &nbsp;
            </tr>
            <tr>
                <td>
                    <button id="btn-fix" onclick="location.href='{% url 'common:login_main' %}'">
                        로그인하기
                    </button>
                </td>
                <td>

                </td>
            </tr>
        </table>
    </div>

</div>

{% endblock %}

django/templates/common/send_email.html
안녕하세요!
PCP 계정 아이디는 다음과 같습니다.

아이디: {{name}}